(Tutorial 01: Basic Square Outline)
(==================================)
(What this does:)
(  Cuts a 40 x 40 mm square outline 2 mm deep into the stock.)
(  One single layer, four straight G1 moves around the perimeter.)
(What to watch for in the simulator:)
(  - Depth-graded toolpath color: green near surface, red/purple at depth)
(  - Spindle LED on the tool: green while M3, orange after M5)
(  - The progress bar fills as time advances)
(  - The orange/wood surface visibly carves down where the tool passes)
(Suggested settings:)
(  Bit diameter: 6 mm 1/4" works fine too))
(  Material thickness: leave at 0 - we're not cutting through the stock)
(  Speed: try 1x first to follow the tool, then crank to 10x or 50x)

G21        (millimeters)
G90        (absolute positioning)
G17        (XY plane)
G0 Z5.0    (rapid to safe-Z)
M3 S12000  (spindle on at 12000 RPM)

G0 X10 Y10     (rapid to start corner)
G1 Z-2.0 F300  (plunge to cut depth at slow Z feed)

G1 X50 Y10 F800   (cut +X edge)
G1 X50 Y50        (cut +Y edge)
G1 X10 Y50        (cut -X edge)
G1 X10 Y10        (back to start - close the loop)

G0 Z5.0    (lift to safe-Z)
G0 X0 Y0   (return home)
M5         (spindle off)
M30        (program end)
